name: Build Monitor

on:
  schedule:
    # Run daily at 9 AM UTC
    - cron: '0 9 * * *'
  workflow_dispatch: # Allow manual triggering

jobs:
  check-deps:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
    
    - name: Setup pnpm
      uses: pnpm/action-setup@v3
      with:
        version: 9
    
    - name: Setup Node.js 22
      uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: 'npm'
    
    - name: Check for outdated dependencies
      run: |
        echo "Checking for outdated dependencies..."
        if [ -f pnpm-lock.yaml ]; then
          pnpm outdated || true
        else
          npm outdated || true
        fi
    
    - name: Security audit
      run: |
        echo "Running security audit..."
        if [ -f pnpm-lock.yaml ]; then
          pnpm audit || true
        else
          npm audit || true
        fi
    
    - name: Summary
      run: |
        echo "## Dependency Health Check Summary" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "✅ Dependency check completed at $(date -u)" >> $GITHUB_STEP_SUMMARY
        echo "" >> $GITHUB_STEP_SUMMARY
        echo "Check the logs above for:"  >> $GITHUB_STEP_SUMMARY
        echo "- Outdated dependencies" >> $GITHUB_STEP_SUMMARY
        echo "- Security vulnerabilities" >> $GITHUB_STEP_SUMMARY